### ISSUE TITLE
where is segmentation folder?

### ISSUE THREAD

**Issue by howthep** [haomo-ai/Cam4DOcc#2]
```
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 200, in main
    meta=meta)
  File "/home/glj/roseupram/Cam4DOcc/projects/occ_plugin/occupancy/apis/train.py", line 27, in custom_train_model
    meta=meta)
  File "/home/glj/roseupram/Cam4DOcc/projects/occ_plugin/occupancy/apis/mmdet_train.py", line 113, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/glj/roseupram/Cam4DOcc/projects/occ_plugin/datasets/cam4docc_dataset.py", line 100, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/glj/roseupram/Cam4DOcc/projects/occ_plugin/datasets/cam4docc_dataset.py", line 312, in prepare_train_data
    example = self.prepare_sequential_data(index)
  File "/home/glj/roseupram/Cam4DOcc/projects/occ_plugin/datasets/cam4docc_dataset.py", line 370, in prepare_sequential_data
    example = self.pipeline(input_seq_data)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/glj/roseupram/Cam4DOcc/projects/occ_plugin/datasets/pipelines/loading_instance.py", line 392, in __call__
    np.savez(seg_label_path, segmentation_saved_list2)
  File "<__array_function__ internals>", line 6, in savez
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/numpy/lib/npyio.py", line 616, in savez
    _savez(file, args, kwds, False)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/numpy/lib/npyio.py", line 712, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: './data/segmentation/2175d0e84f224ea69907e5c338bde395_b60a2bc82d88419497510082d9301a59.npz'
```
where is segmentation folder?

**Comment by BIT-MJY** [comment]
We directly integrate the Cam4DOcc dataset generation pipeline into the dataloader. Please pull our newest code and run again.

**Comment by howthep** [comment]
thanks for your reply, there still are some path error
```
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 114, in main
    plg_lib = importlib.import_module(_module_path)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '..projects.occ_plugin'

```
```
Traceback (most recent call last):
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/datasets/cam4docc_dataset.py", line 67, in __init__
    self.nusc = NuScenes(version='v1.0-trainval', dataroot='/mnt/share_disk/dataset/nuscenes/data', verbose=False)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /mnt/share_disk/dataset/nuscenes/data/v1.0-trainval
```

**Comment by BIT-MJY** [comment]
We have fixed the first bug. The second one is caused by the incorrect nuscenes dataset path. You can follow our data structure to avoid it, but be sure that you have pulled the fresh code.
