### ISSUE TITLE
how much GPU memory do we need?

### ISSUE THREAD

**Issue by howthep** [haomo-ai/Cam4DOcc#3]
thanks for your release
I only have one gpu, memory is 48G, so i run this
```
run.sh ./projects/configs/baselines/OCFNet_in_Cam4DOcc_V1.1.py 1
```
but seems my gpu is not enough
```
RuntimeError: CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 47.54 GiB total capacity; 45.25 GiB already allocated; 18.19 MiB free; 45.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Is there a way to run this code with one 48G gpu

**Comment by howthep** [comment]
after edting "projects/configs/baselines/OCFNet_in_Cam4DOcc_V1.1.py", it works
```
time_receptive_field = 2
n_future_frames = 2
```
but there still some error
```
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/apis/train.py", line 27, in custom_train_model
    meta=meta)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/apis/mmdet_train.py", line 113, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmdet3d-0.17.1-py3.7-linux-x86_64.egg/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/detectors/ocfnet.py", line 477, in forward_train
    img_inputs_seq=img_inputs_seq, img_metas=img_metas, future_egomotion=future_egomotion)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/detectors/ocfnet.py", line 348, in extract_feat
    voxel_feats_enc = self.occ_encoder(voxel_feats)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/detectors/ocfnet.py", line 121, in occ_encoder
    x = self.occ_encoder_backbone(x)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/backbones/resnet3d.py", line 197, in forward
    x = self.input_proj(x)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 590, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 586, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: Given groups=1, weight of size [64, 210, 1, 1, 1], expected input[1, 140, 128, 128, 10] to have 210 channels, but got 140 channels instead

```

**Comment by BIT-MJY** [comment]
Here is my hardware: 8 A100 GPUs with 81251MiB memory for each. Currently our model is a little bit heavy and a large memory is needed. We will figure out a more lightweight solution for this task. 

Sorry for the hard coding on the time_receptive_field and n_future_frames. We will make the code more flexible for this. For the current stage, only using 3 frames to forecast 4 frames is enabled.

**Comment by howthep** [comment]
thanks for your commit, but there still some error
```
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 200, in main
    meta=meta)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/apis/train.py", line 27, in custom_train_model
    meta=meta)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/apis/mmdet_train.py", line 113, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmdet3d-0.17.1-py3.7-linux-x86_64.egg/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/detectors/ocfnet.py", line 513, in forward_train
    points_occ, img_metas, img_feats=img_feats, transform=transform)
  File "/home/glj/miniconda3/envs/cam4docc/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/detectors/ocfnet.py", line 406, in forward_pts_train
    img_metas=img_metas,
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/dense_heads/occ_head.py", line 196, in loss
    loss_dict.update(self.loss_voxel(output_voxel, target_voxels,  tag='c_{}'.format(index)))
  File "/home/glj/roseupram/cam4/projects/occ_plugin/occupancy/dense_heads/occ_head.py", line 155, in loss_voxel
    target_voxels = target_voxels.reshape(B, H, ratio, W, ratio, D, ratio).permute(0,1,3,5,2,4,6).reshape(B, H, W, D, ratio**3)
RuntimeError: shape '[6, 128, 4, 128, 4, 10, 4]' is invalid for input of size 41943040
```

**Comment by BIT-MJY** [comment]
Can you provide your configuration file here? The code runs well on my server.

**Comment by howthep** [comment]
```python
# Cam4DOcc: Benchmark for Camera-Only 4D Occupancy Forecasting in Autonomous Driving Applications
# https://github.com/haomo-ai/Cam4DOcc
# 2 classes: inflated GMO and others

# Basic params ******************************************
_base_ = [
    '../datasets/custom_nus-3d.py',
    '../_base_/default_runtime.py'
]
find_unused_parameters = True
# whether training and test together with dataset generation
only_generate_dataset = False
# we only consider use_camera in Cam4DOcc in the current version
input_modality = dict(
    use_lidar=False,
    use_camera=True,
    use_radar=False,
    use_map=False,
    use_external=False)
plugin = True
plugin_dir = "projects/occ_plugin/"
occ_path = "./data/nuScenes-Occupancy"
depth_gt_path = './data/depth_gt'
train_ann_file = "./data/nuscenes/nuscenes_occ_infos_train.pkl"
val_ann_file = "./data/nuscenes/nuscenes_occ_infos_val.pkl"
cam4docc_dataset_path = "./data/cam4docc/"
nusc_root = './data/nuscenes/'
# GMO class names
class_names = ['vehicle', 'human']
use_separate_classes = False
use_fine_occ = False

# Forecasting-related params ******************************************
# we use *time_receptive_field* past frames to forecast future *n_future_frames* frames
# for 3D instance prediction, n_future_frames_plus > n_future_frames has to be set


################## HERE I CHANGE #######################
time_receptive_field = 2
n_future_frames = 2
################## HERE I CHANGE #######################


n_future_frames_plus = 6
iou_thresh_for_vpq = 0.2
test_present = False

# Occupancy-related params ******************************************
point_cloud_range = [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
occ_size = [512, 512, 40]
lss_downsample = [4, 4, 4]
voxel_x = (point_cloud_range[3] - point_cloud_range[0]) / occ_size[0]
voxel_y = (point_cloud_range[4] - point_cloud_range[1]) / occ_size[1]
voxel_z = (point_cloud_range[5] - point_cloud_range[2]) / occ_size[2]
empty_idx = 0
if use_separate_classes:
    num_cls = len(class_names) + 1
else:
    num_cls = 2
img_norm_cfg = None

# Save params ******************************************
save_pred = False
save_path = "./data/cam4docc/results"

# Data-generation and pipeline params ******************************************
dataset_type = 'Cam4DOccDataset'
file_client_args = dict(backend='disk')
data_config={
    'cams': ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT',
             'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT'],
    'Ncams': 6,
    'input_size': (896, 1600),
    'src_size': (900, 1600),
    # image-view augmentation
    'resize': (-0.06, 0.11),
    'rot': (-5.4, 5.4),
    'flip': False,
    'crop_h': (0.0, 0.0),
    'resize_test': 0.00,
}

bda_aug_conf = dict(
            rot_lim=(-0, 0),
            scale_lim=(0.95, 1.05),
            flip_dx_ratio=0.5,
            flip_dy_ratio=0.5)

train_capacity = 23930 # default: use all sequences
test_capacity = 5119 # default: use all sequences
train_pipeline = [
    dict(type='LoadInstanceWithFlow', cam4docc_dataset_path=cam4docc_dataset_path, grid_size=occ_size, use_flow=True, background=empty_idx, pc_range=point_cloud_range,
                use_separate_classes=use_separate_classes),
    dict(type='LoadMultiViewImageFromFiles_BEVDet', is_train=True, data_config=data_config,
                sequential=False, aligned=True, trans_only=False, depth_gt_path=depth_gt_path,
                mmlabnorm=True, load_depth=True, img_norm_cfg=img_norm_cfg),
    dict(type='LoadOccupancy', to_float32=True, occ_path=occ_path, grid_size=occ_size, unoccupied=empty_idx, pc_range=point_cloud_range, use_fine_occ=use_fine_occ, test_mode=False),
    dict(type='OccDefaultFormatBundle3D', class_names=class_names),
    dict(type='Collect3D', keys=['img_inputs_seq', 'gt_occ', 'segmentation', 'instance', 'flow', 'future_egomotion']),
]

test_pipeline = [
    dict(type='LoadInstanceWithFlow', cam4docc_dataset_path=cam4docc_dataset_path, grid_size=occ_size, use_flow=True, background=empty_idx, pc_range=point_cloud_range,
         use_separate_classes=use_separate_classes),
    dict(type='LoadMultiViewImageFromFiles_BEVDet', data_config=data_config, depth_gt_path=depth_gt_path,
         sequential=False, aligned=True, trans_only=False, mmlabnorm=True, img_norm_cfg=img_norm_cfg, test_mode=True),
    dict(type='LoadOccupancy', to_float32=True, occ_path=occ_path, grid_size=occ_size, unoccupied=empty_idx, pc_range=point_cloud_range, use_fine_occ=use_fine_occ, test_mode=True),
    dict(type='OccDefaultFormatBundle3D', class_names=class_names, with_label=False), 
    dict(type='Collect3D', keys=['img_inputs_seq', 'gt_occ', 'segmentation', 'instance', 'flow', 'future_egomotion'], meta_keys=['pc_range', 'occ_size', 'scene_token', 'lidar_token']),
]

train_config=dict(
        type=dataset_type,
        data_root=nusc_root,
        occ_root=occ_path,
        ann_file=train_ann_file,
        pipeline=train_pipeline,
        classes=class_names,
        use_separate_classes=use_separate_classes,
        modality=input_modality,
        test_mode=False,
        use_valid_flag=True,
        occ_size=occ_size,
        pc_range=point_cloud_range,
        box_type_3d='LiDAR',
        time_receptive_field=time_receptive_field,
        n_future_frames=n_future_frames,
        train_capacity=train_capacity,
        test_capacity=test_capacity,
        ) 

test_config=dict(
    type=dataset_type,
    occ_root=occ_path,
    data_root=nusc_root,
    ann_file=val_ann_file,
    pipeline=test_pipeline,
    classes=class_names,
    use_separate_classes=use_separate_classes,
    modality=input_modality,
    occ_size=occ_size,
    pc_range=point_cloud_range,
    time_receptive_field=time_receptive_field, 
    n_future_frames=n_future_frames,
    train_capacity=train_capacity,
    test_capacity=test_capacity,
    ) 

# in our work we use 8 NVIDIA A100 GPUs
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=train_config,
    val=test_config,
    test=test_config,
    shuffler_sampler=dict(type='DistributedGroupSampler'),
    nonshuffler_sampler=dict(type='DistributedSampler'),
)

# Model params ******************************************
grid_config = {
    'xbound': [point_cloud_range[0], point_cloud_range[3], voxel_x*lss_downsample[0]],
    'ybound': [point_cloud_range[1], point_cloud_range[4], voxel_y*lss_downsample[1]],
    'zbound': [point_cloud_range[2], point_cloud_range[5], voxel_z*lss_downsample[2]],
    'dbound': [2.0, 58.0, 0.5],
}

voxel_channels = [32*(time_receptive_field), 32*2*(time_receptive_field), 32*4*(time_receptive_field), 32*8*(time_receptive_field)]
pred_channels = [32, 32*2, 32*4, 32*8]
decoder_channels = [32*(n_future_frames_plus), 32*2*(n_future_frames_plus), 32*4*(n_future_frames_plus), 32*8*(n_future_frames_plus)]

numC_Trans = 64
occ_encoder_input_channel = (numC_Trans+6)*time_receptive_field
voxel_out_channel = 32*(n_future_frames_plus)
flow_out_channel = 32*(n_future_frames_plus)
voxel_out_channel_per_frame = 32
voxel_out_indices = (0, 1, 2, 3)
my_voxel_out_indices = (0, 1, 2, 3)

model = dict(
    type='OCFNet',
    only_generate_dataset=only_generate_dataset,
    loss_norm=False,
    disable_loss_depth=True,
    point_cloud_range=point_cloud_range,
    time_receptive_field=time_receptive_field,
    n_future_frames=n_future_frames,
    n_future_frames_plus=n_future_frames_plus,
    max_label=num_cls,
    iou_thresh_for_vpq=iou_thresh_for_vpq,
    test_present=test_present,
    record_time=False,
    save_pred=save_pred,
    save_path=save_path,
    img_backbone=dict(
        pretrained='torchvision://resnet50',
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=0,
        with_cp=False,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch'),
    img_neck=dict(
        type='SECONDFPN',
        in_channels=[256, 512, 1024, 2048],
        upsample_strides=[0.25, 0.5, 1, 2],
        out_channels=[128, 128, 128, 128]),
    img_view_transformer=dict(type='ViewTransformerLiftSplatShootVoxel',
                              norm_cfg=dict(type='SyncBN', requires_grad=True),
                              loss_depth_weight=3.,
                              loss_depth_type='kld',
                              grid_config=grid_config,
                              data_config=data_config,
                              numC_Trans=numC_Trans,
                              vp_megvii=False),
    occ_encoder_backbone=dict(
        type='CustomResNet3D',
        depth=18,
        n_input_channels=occ_encoder_input_channel,
        block_inplanes=voxel_channels,
        out_indices=my_voxel_out_indices,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
    ),
    occ_predictor=dict(
        type='Predictor',
        n_input_channels=pred_channels,
        in_timesteps=time_receptive_field,
        out_timesteps=n_future_frames_plus,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
    ),
    occ_encoder_neck=dict(
        type='FPN3D',
        with_cp=False,
        in_channels=decoder_channels,
        out_channels=voxel_out_channel,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
    ),
    flow_encoder_backbone=dict(
        type='CustomResNet3D',
        depth=18,
        n_input_channels=occ_encoder_input_channel,
        block_inplanes=voxel_channels,
        out_indices=my_voxel_out_indices,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
    ),
    flow_predictor=dict(
        type='Predictor',
        n_input_channels=pred_channels,
        in_timesteps=time_receptive_field,
        out_timesteps=n_future_frames_plus,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
    ),
    flow_encoder_neck=dict(
        type='FPN3D',
        with_cp=False,
        in_channels=decoder_channels,
        out_channels=flow_out_channel,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
    ),
    flow_head=dict(
        type='FlowHead',
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        soft_weights=True, 
        final_occ_size=occ_size,
        fine_topk=15000,
        empty_idx=empty_idx,
        num_level=len(my_voxel_out_indices),
        in_channels=[voxel_out_channel_per_frame] * len(my_voxel_out_indices),
        out_channel=3,  # 3-dim flow
        point_cloud_range=point_cloud_range,
    ),
    pts_bbox_head=dict(
        type='OccHead',
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        soft_weights=True,
        final_occ_size=occ_size,
        fine_topk=15000,
        empty_idx=empty_idx,
        num_level=len(my_voxel_out_indices),
        in_channels=[voxel_out_channel_per_frame] * len(my_voxel_out_indices),
        out_channel=num_cls,
        point_cloud_range=point_cloud_range,
        loss_weight_cfg=dict(
            loss_voxel_ce_weight=1.0,
            loss_voxel_sem_scal_weight=1.0,
            loss_voxel_geo_scal_weight=1.0,
            loss_voxel_lovasz_weight=1.0,
        ),
    ),
    empty_idx=empty_idx,
)

# Learning policy params ******************************************
optimizer = dict(
    type='AdamW',
    lr=3e-4,   
    paramwise_cfg=dict(
        custom_keys={
            'img_backbone': dict(lr_mult=0.1),
        }),
    weight_decay=0.01)

optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='CosineAnnealing',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    min_lr_ratio=1e-3)

runner = dict(type='EpochBasedRunner', max_epochs=24)
evaluation = dict(
    interval=1,
    pipeline=test_pipeline,
    save_best='SSC_mean',
    rule='greater',
)

custom_hooks = [
    dict(type='OccEfficiencyHook'),
]

```

**Comment by BIT-MJY** [comment]
Please set `n_future_frames_plus` as 4 or 3. Please make sure that `n_future_frames_plus <= time_receptive_field + n_future_frames` because `n_future_frames_plus` means the real prediction number. We forecast more frames rather than only `n_future_frames`.

**Comment by howthep** [comment]
yes, it works.
Thank you for your dedication and support, it saves my life.

**Comment by cuge1995** [comment]
Is it possible to run with GPU memory 24 GB?

**Comment by BIT-MJY** [comment]
@cuge1995  Thanks for your interest in our work. We have not tried with other types of GPUs, but we are working on a lightweight version of OCFNet and will release it in the future.
